apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: heatpump-monitoring
      defaultBucket: heatpump-data
      tlsSkipVerify: true
    secureJsonData:
      token: $__env{INFLUXDB_TOKEN}
    editable: true
    isDefault: true
