heatpumps:
- id: hp1
  name: Main Heat Pump
  location: Basement
  model: stiebel_eltron_wpm
  enabled: true
  modbus:
    type: tcp
    host: 192.168.0.126
    port: 502
    unit_id: 1
    timeout: 5.0
    retries: 3
    retry_delay: 1.0
- id: hp-1
  name: Heat Pump1
  location: Garage
  model: stiebel_eltron_wpm
  enabled: true
  modbus:
    type: tcp
    host: 192.168.8.74
    port: 502
    unit_id: 1
    timeout: 5.0
    retries: 3
    retry_delay: 1.0
